---

- hosts: all
  become: true
  tasks:
  - name: installing apache server
    apt:
      name:
       - apache2
       - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"
