---

- hosts: all
  become: true
  tasks:
  - name: installing apache server
    apt:
      name: apache2
    when: ansible_distribution == "ubuntu"
  - name: installing  php support
    apt:
      name: libapache2-mod-php
